//go:build ignore

// gen regenerates tables.go: the Unicode 17.0.0 data internal/person needs to
// normalize and case-fold a person identifier, held in this repository so the
// fold does not depend on whichever Unicode version the compiler's standard
// library or golang.org/x/text happened to ship.
//
// Run it from this directory under Go 1.27:
//
//	go run gen.go
//
// It asks golang.org/x/text the same per-rune questions internal/person used
// to ask at runtime (single-rune NFD, combining class, boundary-before,
// guarded two-rune composition, per-rune case folding) and stdlib unicode for
// assigned-ness, over every Unicode scalar value. That is the same provenance
// discipline internal/textsafe's Cc/Cf table already uses: no network, no UCD
// text files committed, and the answers are the ones the rest of the package
// was already vetted against (the exhaustive CPython differential in
// internal/person's tests). It refuses to run unless every source it reads is
// Unicode 17.0.0, so a toolchain bump can never quietly change the tables.
//
// Hangul syllables are not tabled: their decomposition and composition are
// algorithmic (UAX #15 §3.12) and live in ucd.go.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strconv"
	"unicode"

	"golang.org/x/text/cases"
	"golang.org/x/text/unicode/norm"
)

const version = "17.0.0"

const (
	hangulBase  = 0xAC00
	hangulCount = 11172
)

func main() {
	if norm.Version != version || cases.UnicodeVersion != version || unicode.Version != version {
		log.Fatalf("refusing to generate: norm is Unicode %s, cases is Unicode %s, unicode is Unicode %s; all three must be %s (run under Go 1.27)",
			norm.Version, cases.UnicodeVersion, unicode.Version, version)
	}

	var (
		decomp   []entry    // single-rune canonical full decomposition
		ccc      []rangeVal // non-zero Canonical_Combining_Class
		nonBound []rangeVal // BoundaryBefore false (value is always 1)
		fold     []entry    // full default case folding, where it changes the rune
		assigned []rangeVal // General_Category other than Cn (value is always 1)
		fullOf   = map[rune][]rune{}
	)

	fc := cases.Fold()
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if r >= 0xD800 && r <= 0xDFFF {
			continue
		}
		s := string(r)

		if d := norm.NFD.String(s); d != s && !isHangulSyllable(r) {
			decomp = append(decomp, entry{r, d})
			fullOf[r] = []rune(d)
		}

		p := norm.NFC.PropertiesString(s)
		if c := p.CCC(); c != 0 {
			ccc = appendRange(ccc, r, int(c))
		}
		if !p.BoundaryBefore() {
			nonBound = appendRange(nonBound, r, 1)
		}

		f := fc.String(s)
		// Cherokee is the one script whose folding maps lowercase *up*, and
		// x/text's XOR-delta encoding cannot express that: it toggles
		// U+13A0..U+13F5 where CaseFolding.txt holds them fixed
		// (golang/go#46101). The vendored table holds them fixed, which is
		// what the specification says, so nothing downstream has to know.
		if r >= 0x13A0 && r <= 0x13F5 {
			f = s
		}
		if f != s {
			fold = append(fold, entry{r, f})
		}

		// Everything but Cn. unicode.C is the whole Other category and takes
		// the unassigned code points with it, so Cc, Cf and Co are named.
		if unicode.In(r, unicode.L, unicode.M, unicode.N, unicode.P, unicode.S, unicode.Z, unicode.Cc, unicode.Cf, unicode.Co) {
			assigned = appendRange(assigned, r, 1)
		}
	}

	compose := composePairs(decomp, fullOf)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen.go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package ucd\n\n")
	fmt.Fprintf(&b, "// Unicode %s. Regenerate with `go generate` (Go 1.27).\n\n", version)

	fmt.Fprintf(&b, "// decompTable lists every code point with a canonical decomposition, other than\n")
	fmt.Fprintf(&b, "// Hangul syllables, with its full (recursive) decomposition.\n")
	fmt.Fprintf(&b, "var decompTable = [...]strEntry{\n")
	for _, e := range decomp {
		fmt.Fprintf(&b, "\t{%#X, %s},\n", e.r, strconv.QuoteToASCII(e.s))
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// cccTable lists the code points with a non-zero Canonical_Combining_Class.\n")
	fmt.Fprintf(&b, "var cccTable = [...]cccRange{\n")
	for _, e := range ccc {
		fmt.Fprintf(&b, "\t{%#X, %#X, %d},\n", e.lo, e.hi, e.val)
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// nonBoundaryTable lists the code points a normalization segment may not begin\n")
	fmt.Fprintf(&b, "// at: a non-zero combining class, or ccc 0 but able to compose with what\n")
	fmt.Fprintf(&b, "// precedes it.\n")
	fmt.Fprintf(&b, "var nonBoundaryTable = [...]runeRange{\n")
	for _, e := range nonBound {
		fmt.Fprintf(&b, "\t{%#X, %#X},\n", e.lo, e.hi)
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// composeTable lists the primary composites, composition exclusions already\n")
	fmt.Fprintf(&b, "// applied, other than Hangul syllables: (first, second) -> composite, sorted\n")
	fmt.Fprintf(&b, "// by (first, second).\n")
	fmt.Fprintf(&b, "var composeTable = [...]composeEntry{\n")
	for _, e := range compose {
		fmt.Fprintf(&b, "\t{%#X, %#X, %#X},\n", e.a, e.b, e.c)
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// foldTable lists the code points whose full default case folding (the C and F\n")
	fmt.Fprintf(&b, "// entries of CaseFolding.txt) differs from themselves.\n")
	fmt.Fprintf(&b, "var foldTable = [...]strEntry{\n")
	for _, e := range fold {
		fmt.Fprintf(&b, "\t{%#X, %s},\n", e.r, strconv.QuoteToASCII(e.s))
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// assignedTable lists the code points whose General_Category is not Cn.\n")
	fmt.Fprintf(&b, "var assignedTable = [...]runeRange{\n")
	for _, e := range assigned {
		fmt.Fprintf(&b, "\t{%#X, %#X},\n", e.lo, e.hi)
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("formatting generated source: %v", err)
	}
	if err := os.WriteFile("tables.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("tables.go: %d decompositions, %d ccc ranges, %d non-boundary ranges, %d compositions, %d folds, %d assigned ranges",
		len(decomp), len(ccc), len(nonBound), len(compose), len(fold), len(assigned))
}

type entry struct {
	r rune
	s string
}

type rangeVal struct {
	lo, hi rune
	val    int
}

type pair struct{ a, b, c rune }

func isHangulSyllable(r rune) bool { return r >= hangulBase && r < hangulBase+hangulCount }

func isHangulJamoPair(a, b rune) bool {
	switch {
	case a >= 0x1100 && a < 0x1100+19 && b >= 0x1161 && b < 0x1161+21:
		return true // L + V
	case isHangulSyllable(a) && (a-hangulBase)%28 == 0 && b > 0x11A7 && b < 0x11A7+28:
		return true // LV + T
	}
	return false
}

// appendRange extends the last range when r is adjacent to it and carries the
// same value, and starts a new one otherwise. Calls arrive in ascending order.
func appendRange(rs []rangeVal, r rune, val int) []rangeVal {
	if n := len(rs); n > 0 && rs[n-1].hi+1 == r && rs[n-1].val == val {
		rs[n-1].hi = r
		return rs
	}
	return append(rs, rangeVal{r, r, val})
}

// composePairs derives the primary composition table. A primary composite's
// canonical mapping is a pair (a, b) whose full decompositions concatenate to
// the composite's own, so the candidates for each decomposable code point are
// the splits of its full decomposition, and every candidate pair is put to
// x/text's two-rune composition, guarded by a round trip through NFD exactly as
// internal/person used to do at runtime: x/text packs a pair into a 32-bit key
// as uint16(a)<<16|uint16(b), so a starter above U+FFFF is truncated to its low
// 16 bits and falsely composes with a BMP mark (NFC of U+10041 U+0300 is "À").
// A false composition is not canonically equivalent to its input, which is
// what the guard catches.
func composePairs(decomp []entry, fullOf map[rune][]rune) []pair {
	byFull := map[string][]rune{}
	for r, d := range fullOf {
		byFull[string(d)] = append(byFull[string(d)], r)
	}
	// candidates returns every code point whose full decomposition is seq: the
	// decomposable ones, plus seq's own rune when it is a single code point that
	// does not decompose.
	candidates := func(seq []rune) []rune {
		out := append([]rune(nil), byFull[string(seq)]...)
		if len(seq) == 1 {
			if _, decomposes := fullOf[seq[0]]; !decomposes {
				out = append(out, seq[0])
			}
		}
		return out
	}

	seen := map[[2]rune]rune{}
	for _, e := range decomp {
		d := fullOf[e.r]
		for k := 1; k < len(d); k++ {
			for _, a := range candidates(d[:k]) {
				for _, b := range candidates(d[k:]) {
					if isHangulJamoPair(a, b) {
						continue
					}
					if c, ok := combine(a, b); ok {
						seen[[2]rune{a, b}] = c
					}
				}
			}
		}
	}
	out := make([]pair, 0, len(seen))
	for k, c := range seen {
		out = append(out, pair{k[0], k[1], c})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].a != out[j].a {
			return out[i].a < out[j].a
		}
		return out[i].b < out[j].b
	})
	return out
}

// combine is the two-rune composition question with the round-trip guard.
func combine(a, b rune) (rune, bool) {
	in := string([]rune{a, b})
	out := norm.NFC.String(in)
	if norm.NFD.String(out) != norm.NFD.String(in) {
		return 0, false
	}
	rs := []rune(out)
	if len(rs) == 1 {
		return rs[0], true
	}
	return 0, false
}
