// Package ucd holds the Unicode 17.0.0 data internal/person's normalization
// rule is defined over: canonical decomposition, combining classes,
// composition, case folding and the assigned-code-point set.
//
// spec/identifiers.md pins the person-identifier fold to Unicode 17.0.0
// permanently for format v1, so the data is vendored here as generated tables
// rather than read from the compiler's standard library or golang.org/x/text,
// both of which select their Unicode version by Go release. A fold that
// consulted them would give a signed log a folded state that depended on who
// built the reader.
//
// tables.go is generated by gen.go; see the go:generate line below. This
// package imports nothing outside sort, and is pure table lookup: no
// filesystem, no network, no process spawning, no clock. internal/person's
// entry in the fold's import allowlist grants nothing more because of it.
package ucd

//go:generate go run gen.go

import "sort"

// Version is the Unicode version every table in this package was generated
// from.
const Version = "17.0.0"

// Hangul syllable constants, UAX #15 §3.12 / the Unicode Standard §3.12. A
// precomposed Hangul syllable decomposes to jamo, and jamo compose back,
// by arithmetic rather than by table.
const (
	sBase  = 0xAC00
	lBase  = 0x1100
	vBase  = 0x1161
	tBase  = 0x11A7
	lCount = 19
	vCount = 21
	tCount = 28
	nCount = vCount * tCount
	sCount = lCount * nCount
)

type (
	strEntry struct {
		r rune
		s string
	}
	runeRange struct{ lo, hi rune }
	cccRange  struct {
		lo, hi rune
		c      uint8
	}
	composeEntry struct{ a, b, c rune }
)

// Decompose returns r's full canonical decomposition, or "" when r has none.
func Decompose(r rune) string {
	if r < 0xC0 {
		return "" // the first canonical decomposition is U+00C0
	}
	if r >= sBase && r < sBase+sCount {
		s := r - sBase
		l, v, t := lBase+s/nCount, vBase+s%nCount/tCount, tBase+s%tCount
		if t == tBase {
			return string([]rune{l, v})
		}
		return string([]rune{l, v, t})
	}
	i := sort.Search(len(decompTable), func(i int) bool { return decompTable[i].r >= r })
	if i < len(decompTable) && decompTable[i].r == r {
		return decompTable[i].s
	}
	return ""
}

// CCC returns r's Canonical_Combining_Class; 0 for a starter.
func CCC(r rune) uint8 {
	if r < 0x300 {
		return 0 // the first non-starter is U+0300
	}
	i := sort.Search(len(cccTable), func(i int) bool { return cccTable[i].hi >= r })
	if i < len(cccTable) && cccTable[i].lo <= r {
		return cccTable[i].c
	}
	return 0
}

// Compose returns the primary composite of a followed by b, if there is one.
// Composition exclusions are already applied, so a pair that only an excluded
// composite decomposes to does not compose.
func Compose(a, b rune) (rune, bool) {
	switch {
	case a >= lBase && a < lBase+lCount && b >= vBase && b < vBase+vCount:
		return sBase + ((a-lBase)*vCount+(b-vBase))*tCount, true
	case a >= sBase && a < sBase+sCount && (a-sBase)%tCount == 0 && b > tBase && b < tBase+tCount:
		return a + (b - tBase), true
	}
	i := sort.Search(len(composeTable), func(i int) bool {
		e := composeTable[i]
		return e.a > a || e.a == a && e.b >= b
	})
	if i < len(composeTable) && composeTable[i].a == a && composeTable[i].b == b {
		return composeTable[i].c, true
	}
	return 0, false
}

// BoundaryBefore reports whether a normalization segment may begin at r: r is
// a starter and does not compose with whatever precedes it. A position where
// this holds is one nothing can compose across, so cutting a string there
// cannot separate a composing pair. Hangul V and T jamo and spacing marks such
// as Grantha U+1133E and Tamil U+0BBE are starters that combine backward, so
// they report false.
func BoundaryBefore(r rune) bool {
	if r < 0x300 {
		return true // the first non-boundary is U+0300
	}
	return !inRanges(nonBoundaryTable[:], r)
}

// Fold returns r's full default case folding (UAX #21 §2.3 toCasefold: the C
// and F entries of CaseFolding.txt, no Turkic tailoring) when it differs from
// r, and "" when r folds to itself. Cherokee U+13A0..U+13F5 are fixed points.
func Fold(r rune) string {
	i := sort.Search(len(foldTable), func(i int) bool { return foldTable[i].r >= r })
	if i < len(foldTable) && foldTable[i].r == r {
		return foldTable[i].s
	}
	return ""
}

// Assigned reports whether r has a General_Category other than Cn: it is
// assigned at Unicode 17.0.0, or private use. Noncharacters are Cn.
func Assigned(r rune) bool {
	return inRanges(assignedTable[:], r)
}

func inRanges(rs []runeRange, r rune) bool {
	i := sort.Search(len(rs), func(i int) bool { return rs[i].hi >= r })
	return i < len(rs) && rs[i].lo <= r
}
