package spec_test

import (
	"os"
	"strings"
	"testing"
)

// The reference fold carries its own copy of the person-identifier folding
// algorithm, because reffold.go is what an implementer in another language
// reads and it deliberately imports no engine code. Two copies drift.
//
// TestReffoldNormalizePersonMatchesEngine covers that behaviourally, but only
// over inputs somebody thought to write down: when the engine was changed to
// compose segments itself and reffold.go was left on the old dual path, that
// table had no case that could tell them apart, and the divergence reached a
// pushed branch. The fixtures every other implementation is checked against
// are produced by reffold.go, so it is the copy that must not be the weaker
// one.
//
// This test compares the two as source, which is cruder than a behavioural
// test on purpose: it compares the entire shared person normalization
// algorithm (FoldValue/foldPersonValue down through ccc/personCCC) and fails
// on any edit made to one copy and not the other, including edits whose
// behaviour a test table would not distinguish.
const (
	engineSource  = "../internal/person/person.go"
	engineFirst   = "// FoldValue applies the value half of the normalization rule in"
	engineLast    = "func ccc(r rune) uint8 {"
	reffoldSource = "reffold.go"
	reffoldFirst  = "// foldPersonValue applies the value half of the normalization rule in"
	reffoldLast   = "func personCCC(r rune) uint8 {"
)

// reffoldRenames maps the reference copy's names onto the engine's. Longest
// first to prevent prefix collisions (e.g. personNFCSegment before personNFC).
var reffoldRenames = [][2]string{
	{"personSortRunInsertionMax", "sortRunInsertionMax"},
	{"personUnicodeVersion", "UnicodeVersion"},
	{"personCanonicalOrder", "canonicalOrder"},
	{"personHasCherokee", "hasCherokeeFoldedRune"},
	{"personCherokeeHi", "cherokeeFoldedHi"},
	{"personCherokeeLo", "cherokeeFoldedLo"},
	{"personNFCSegment", "nfcSegment"},
	{"personLowerASCII", "lowerASCII"},
	{"personSegmentLen", "segmentLen"},
	{"foldPersonValue", "FoldValue"},
	{"personFoldCaser", "foldCaser"},
	{"personSortByCCC", "sortByCCC"},
	{"personDecompose", "decompose"},
	{"personCaseFold", "caseFold"},
	{"personIsASCII", "isASCII"},
	{"personCompose", "compose"},
	{"personCombine", "combine"},
	{"personCCC", "ccc"},
	{"personNFC", "nfc"},
}

func TestReffoldIsTheSameAlgorithmAsTheEngine(t *testing.T) {
	engine := extractBlock(t, engineSource, engineFirst, engineLast)
	reffold := extractBlock(t, reffoldSource, reffoldFirst, reffoldLast)
	for _, r := range reffoldRenames {
		reffold = strings.ReplaceAll(reffold, r[0], r[1])
	}
	if engine == reffold {
		return
	}
	engineLines := strings.Split(engine, "\n")
	reffoldLines := strings.Split(reffold, "\n")
	for i := 0; i < len(engineLines) || i < len(reffoldLines); i++ {
		var e, r string
		if i < len(engineLines) {
			e = engineLines[i]
		}
		if i < len(reffoldLines) {
			r = reffoldLines[i]
		}
		if e != r {
			t.Fatalf("%s and %s have diverged at line %d of the folding block:\n engine:  %s\n reffold: %s\n\n"+
				"Both copies implement the same algorithm and the conformance fixtures are "+
				"generated by the reference one. Port the change rather than leaving them different.",
				engineSource, reffoldSource, i+1, e, r)
		}
	}
	t.Fatalf("%s and %s differ in length: %d vs %d lines",
		engineSource, reffoldSource, len(engineLines), len(reffoldLines))
}

// extractBlock returns the source between first and the end of the function
// starting at last, so the comparison covers exactly the shared algorithm and
// not the rest of either file.
func extractBlock(t *testing.T, path, first, last string) string {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	src := string(raw)
	a := strings.Index(src, first)
	if a < 0 {
		t.Fatalf("%s no longer contains %q; update this test deliberately", path, first)
	}
	b := strings.Index(src, last)
	if b < 0 {
		t.Fatalf("%s no longer contains %q; update this test deliberately", path, last)
	}
	end := strings.Index(src[b:], "\n}\n")
	if end < 0 {
		t.Fatalf("%s: could not find the end of %q", path, last)
	}
	return strings.TrimSpace(src[a : b+end])
}
